services:
  - type: web
    name: komunaid-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: PASSWORD_RESET_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 30d
      - key: BCRYPT_SALT_ROUNDS
        value: "12"
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: "1025"
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASS
        value: ""
      - key: SMTP_FROM
        value: "KomunaID <noreply@komuna.id>"
    healthCheckPath: /api/v1/health/ready
    autoDeploy: true
