@extends('layouts.admin')

@section('content')
<div class="max-w-7xl mx-auto">
    <div class="flex items-center justify-between mb-6">
        <div>
            <h1 class="text-2xl font-bold text-[#0B2D89]">SDLC Documentation</h1>
            <p class="text-sm text-[#64748B] mt-1">Generate dan manage dokumentasi project KomunaID V2</p>
        </div>
        <div class="flex items-center gap-3">
            <a href="{{ route('superadmin.documentation.tools.routes') }}" class="inline-flex items-center gap-2 px-4 py-2 bg-white border border-[#E2E8F0] text-[#64748B] rounded-lg text-sm font-medium hover:bg-komuna-surface transition">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg>
                Route Inventory
            </a>
            <a href="{{ route('superadmin.documentation.tools.database') }}" class="inline-flex items-center gap-2 px-4 py-2 bg-white border border-[#E2E8F0] text-[#64748B] rounded-lg text-sm font-medium hover:bg-komuna-surface transition">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4"/></svg>
                Database Inventory
            </a>
            <a href="{{ route('superadmin.documentation.generate.index') }}" class="inline-flex items-center gap-2 px-4 py-2 bg-[#126BFF] text-white rounded-lg text-sm font-medium hover:bg-[#0B2D89] transition">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>
                Generate Dokumen
            </a>
        </div>
    </div>

    {{-- Stats --}}
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        <div class="bg-white rounded-xl border border-[#E2E8F0] p-4">
            <div class="text-sm text-[#64748B]">Total Dokumen</div>
            <div class="text-2xl font-bold text-[#0B2D89]">{{ $documents->total() }}</div>
        </div>
        <div class="bg-white rounded-xl border border-[#E2E8F0] p-4">
            <div class="text-sm text-[#64748B]">Generated</div>
            <div class="text-2xl font-bold text-green-600">{{ $documents->where('status', 'generated')->count() }}</div>
        </div>
        <div class="bg-white rounded-xl border border-[#E2E8F0] p-4">
            <div class="text-sm text-[#64748B]">Failed</div>
            <div class="text-2xl font-bold text-red-600">{{ $documents->where('status', 'failed')->count() }}</div>
        </div>
        <div class="bg-white rounded-xl border border-[#E2E8F0] p-4">
            <div class="text-sm text-[#64748B]">Draft</div>
            <div class="text-2xl font-bold text-yellow-600">{{ $documents->where('status', 'draft')->count() }}</div>
        </div>
    </div>

    {{-- Document List --}}
    <div class="bg-white rounded-xl border border-[#E2E8F0] overflow-hidden">
        <div class="px-6 py-4 border-b border-[#E2E8F0]">
            <h2 class="text-lg font-semibold text-[#0B2D89]">Daftar Dokumen</h2>
        </div>

        @if($documents->count() > 0)
            <div class="overflow-x-auto">
                <table class="w-full text-sm">
                    <thead class="bg-[#EEF7FF]">
                        <tr>
                            <th class="text-left px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Judul</th>
                            <th class="text-left px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Key</th>
                            <th class="text-left px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Type</th>
                            <th class="text-left px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Format</th>
                            <th class="text-left px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Status</th>
                            <th class="text-left px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Generated At</th>
                            <th class="text-left px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Generated By</th>
                            <th class="text-right px-6 py-3 text-xs font-semibold text-[#64748B] uppercase">Aksi</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-[#E2E8F0]">
                        @foreach($documents as $doc)
                            <tr class="hover:bg-komuna-surface transition">
                                <td class="px-6 py-4">
                                    <div class="font-medium text-[#0F172A]">{{ $doc->title }}</div>
                                    @if($doc->summary)
                                        <div class="text-xs text-[#64748B] mt-1 line-clamp-1">{{ Str::limit($doc->summary, 80) }}</div>
                                    @endif
                                </td>
                                <td class="px-6 py-4">
                                    <code class="text-xs bg-[#EEF7FF] text-[#126BFF] px-2 py-1 rounded">{{ $doc->document_key ?? '-' }}</code>
                                </td>
                                <td class="px-6 py-4 text-[#64748B]">{{ $doc->document_type }}</td>
                                <td class="px-6 py-4">
                                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-komuna-border-soft text-komuna-text uppercase">{{ $doc->format }}</span>
                                </td>
                                <td class="px-6 py-4">{!! $doc->status_badge !!}</td>
                                <td class="px-6 py-4 text-[#64748B] text-xs">{{ $doc->generated_at ? $doc->generated_at->format('d M Y H:i') : '-' }}</td>
                                <td class="px-6 py-4 text-[#64748B] text-xs">{{ $doc->generatedByUser?->name ?? '-' }}</td>
                                <td class="px-6 py-4 text-right">
                                    <div class="flex items-center justify-end gap-2">
                                        <a href="{{ route('superadmin.documentation.show', $doc) }}" class="text-[#126BFF] hover:text-[#0B2D89] transition" title="View">
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                                        </a>
                                        <a href="{{ route('superadmin.documentation.preview', $doc) }}" class="text-[#64748B] hover:text-[#0B2D89] transition" title="Preview">
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>
                                        </a>
                                        <a href="{{ route('superadmin.documentation.download', $doc) }}" class="text-[#16A34A] hover:text-green-700 transition" title="Download">
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                                        </a>
                                        <form method="POST" action="{{ route('superadmin.documentation.destroy', $doc) }}" class="inline" onsubmit="return confirm('Yakin ingin menghapus dokumen ini?')">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="text-red-500 hover:text-red-700 transition" title="Delete">
                                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="px-6 py-4 border-t border-[#E2E8F0]">
                {{ $documents->links() }}
            </div>
        @else
            <div class="px-6 py-16 text-center">
                <svg class="w-16 h-16 mx-auto text-[#E2E8F0] mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                <p class="text-[#64748B] mb-4">Belum ada dokumen yang di-generate</p>
                <a href="{{ route('superadmin.documentation.generate.index') }}" class="inline-flex items-center gap-2 px-4 py-2 bg-[#126BFF] text-white rounded-lg text-sm font-medium hover:bg-[#0B2D89] transition">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>
                    Generate Sekarang
                </a>
            </div>
        @endif
    </div>
</div>
@endsection
