ALTER TABLE `volunteer_programs`
  MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REVISION_REQUIRED', 'REJECTED', 'APPROVED', 'SCHEDULED', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT';

CREATE TABLE `volunteer_program_status_histories` (
  `id` VARCHAR(191) NOT NULL,
  `volunteerProgramId` VARCHAR(191) NOT NULL,
  `previousStatus` ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REVISION_REQUIRED', 'REJECTED', 'APPROVED', 'SCHEDULED', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'ARCHIVED') NOT NULL,
  `newStatus` ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REVISION_REQUIRED', 'REJECTED', 'APPROVED', 'SCHEDULED', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'ARCHIVED') NOT NULL,
  `actorId` VARCHAR(191) NOT NULL,
  `actorRole` VARCHAR(191) NULL,
  `reason` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `vpsh_program_created_idx`(`volunteerProgramId`, `createdAt`),
  INDEX `vpsh_actor_idx`(`actorId`),
  CONSTRAINT `vpsh_program_fk` FOREIGN KEY (`volunteerProgramId`) REFERENCES `volunteer_programs`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `vpsh_actor_fk` FOREIGN KEY (`actorId`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
