-- AlterEnum
ALTER TABLE `community_members` MODIFY COLUMN `status` ENUM('ACTIVE', 'PENDING', 'REJECTED', 'BANNED', 'LEFT') NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `organization_members` MODIFY COLUMN `status` ENUM('ACTIVE', 'PENDING', 'REJECTED', 'BANNED', 'LEFT') NOT NULL DEFAULT 'ACTIVE';
